---
- hosts: devops
  become: yes
  tasks:
 
  - name: Add user to remote hosts
    user: name=user1 groups=sudo shell=/bin/bash

  - name: Add SSH keys to remote hosts
    authorized_key: user=user1 key="{{ lookup('file', "~/.ssh/user1.pub") }}"
